[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecdsa = "0.16.9"
hex-literal = "0.4.1"
p256 = "0.13.2"
sha2 = "0.10.8"
twizzler-abi = { path = "../../lib/twizzler-abi", features = ["runtime"] }

[package.metadata]
twizzler-build = "static"
