[package]
name = "lethe-gadget-fat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twizzler-abi = { path = "../../../lib/twizzler-abi" }
layout = { path = "./layout" }
kms = { path = "../../../lib/kms" }
getrandom = { path = "../../../lib/getrandom-twizzler" }
rand = "0.8.5"
chacha20 = { version = "0.9.1", features = ["zeroize"] }
#[package.metadata]
#twizzler-build = "static"
